services:
  postgres:
    image: postgres:16
    container_name: postgres-portfolio
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: portfolio_db       # ← new DB name
    ports:
      - "5440:5432"                   # ← new host port mapped to container's 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/db/postgresql/profileDB.sql:/docker-entrypoint-initdb.d/database.sql:ro

volumes:
  postgres_data:
    driver: local


